### ISSUE TITLE
Problem finding root element

### ISSUE THREAD

**Issue by christian-bromann** [baruchvlz/resq#15]
When running resq on http://todomvc.com/examples/react/#/ it has problems finding the root element. When trying to fetch an element it returns an error saying: `Could not find the root element of your application`

**Comment by christian-bromann** [comment]
Same for http://pl12133.github.io/react-solitaire/

**Comment by baruchvlz** [comment]
This is due to the library only supporting React v16+. The TodoMVC example is written in React v0.13.3 which was released almost [4 years ago](https://reactjs.org/blog/2015/05/08/react-v0.13.3.html). I'm not sure if we want to support versions that far back.

I think we can add something to the message saying to make sure they're using v16+.

**Comment by christian-bromann** [comment]
Yeah .. let's note this in the Readme.md so people know that it only works with React v16+

**Comment by baruchvlz** [comment]
Added here: ec4c8ac14875758767cfb0c021a50e91a6243558
