### ISSUE TITLE
Won't Find Root If React Mounted Asynchronously

### ISSUE THREAD

**Issue by lcharbon** [baruchvlz/resq#31]
Related to Webdriverio issue [3916](https://github.com/webdriverio/webdriverio/issues/3916).

If react is mounted asynchronously. Using react$ selector throws the error:
`javascript error: Could not find the root element of your application`.

I see two cases for mounting react asynchronously:

1) React is only used for a subset of the app.
2) React needs to request for external data before it is mounted.

**Comment by baruchvlz** [comment]
As mentioned in the WDIO ticket, I fail to see why you would mount the page asynchronously. Maybe if you can provide a good use case for this then we might think of a reason why to try and fix it, but I myself can't think of a use case and I've never seen anyone do this before.

**Comment by lcharbon** [comment]
@baruchvlz I provided two use cases:

1) React is only used for a subset of the app.
2) React needs to request for external data before it is mounted.

**Comment by baruchvlz** [comment]
My apologies.

 I've never seen anyone mount React asynchronously, what I've seen before though is mounting the app and asynchronously displaying the components. 

From the top of my head, some ways to implement this:

1. Loop through the DOM until it's found, irregardless of how many times this has to be done (obviously it will have to have a max amount of tries)
2. Pass a property to `waitToLoadReact` to wait, in ms, some time before looping through the DOM tree

The reason I'm so hesitant to do this is because neither of the 2 ideas mentioned above will guarantee that the app will be found.

With all this said, there is another idea that might be a work around for this but it requires a new feature that I'm still working on and is the ability to pass a HTML element to the `resq` methods in which will be used as the starting point for creating the tree.

Example:

```js
// index.jsx

const MyComponent = () => <div>Hello World</div>

ReactDOM.render(<div id="bar"><MyComponent /><div>, document.querySelector('#root'))


resq$('MyComponent', document.querySelector('#bar'))
```

With this, you can do the query for the element in your tests after your asynchronous methods are completed.

**Comment by baruchvlz** [comment]
With v1.5.0 you can do something like:

```js
const root = document.getElementById('root')

const myComponentInstance = resq$('MyComponent', root)
```

Now, this won't fix the case where the application is mounted asynchronously, but it can give you more more freedom to handle it yourself.

For example:
```js
setTimeout(() => {
  const root = document.getElementById('root')
  const myComponentInstance = resq$('MyComponent', root)
}, 1500)
```

As to how to handle this in WDIO, the react selectors were added as commands to the element, so you can do something like this now

```js
const root = document.getElementById('root')
const myComponentInstance = root.react$('MyComponent')
```
