### ISSUE TITLE
Material-ui-icons Component element.node is null

### ISSUE THREAD

**Issue by moeyashi** [baruchvlz/resq#40]
I use [@material-ui/icons](https://www.npmjs.com/package/@material-ui/icons).
And test it with [WebDriverIO's react$](https://webdriver.io/docs/api/browser/react$.html).
In resq/utils/findStateNode, element.stateNode of material-ui-icon component is null, element.child.stateNode too.
I found element.child.child.child.child.stateNode is svg.
I think findStateNode function need recursive.

<img width="1197" alt="screen shot" src="https://user-images.githubusercontent.com/49895682/63672459-f5345d80-c81c-11e9-8d3e-4d4d63f74c42.png">

**Comment by baruchvlz** [comment]
What version are you using?

**Comment by moeyashi** [comment]
Thank you for your reply!

I'm using `"webdriverio": "^5.12.4"`.
package.json of resq in my node_modules show `"version": "1.6.0"`

I show my dependencies
```json
  "dependencies": {
    "@date-io/date-fns": "^1.3.9",
    "@material-ui/core": "^4.3.3",
    "@material-ui/icons": "^4.2.1",
    "@material-ui/pickers": "^3.2.4",
    "@wdio/sync": "^5.12.3",
    "date-fns": "^2.0.1",
    "isomorphic-unfetch": "^3.0.0",
    "jss": "^9.8.7",
    "next": "^9.0.5",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-jss": "^8.6.1",
    "react-redux": "^7.1.0",
    "redux": "^4.0.3",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/register": "^7.5.5",
    "@storybook/addon-actions": "^5.1.11",
    "@storybook/addon-links": "^5.1.11",
    "@storybook/addon-storyshots": "^5.1.11",
    "@storybook/addons": "^5.1.11",
    "@storybook/react": "^5.1.11",
    "@wdio/cli": "^5.12.4",
    "@wdio/dot-reporter": "^5.12.1",
    "@wdio/local-runner": "^5.12.4",
    "@wdio/mocha-framework": "^5.12.1",
    "@wdio/selenium-standalone-service": "^5.12.1",
    "@wdio/spec-reporter": "^5.12.1",
    "babel-jest": "^24.9.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-require-context-hook": "^1.0.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "jest": "^24.9.0",
    "react-addons-test-utils": "15.6.2",
    "react-test-renderer": "^16.9.0",
    "redux-mock-store": "^1.5.3",
    "selenium-standalone": "^6.16.0",
    "webdriverio": "^5.12.4"
  }
```

**Comment by moeyashi** [comment]
I tried simple code, but it failed.
https://github.com/moeyashi/material-ui-with-webdriberio

Is this attempt helpful?

**Comment by baruchvlz** [comment]
I wonder if the issue is with MaterialUI or with NextJS. I'll take a look at the repository later today.

**Comment by baruchvlz** [comment]
After some investigation I was able to figure out what's going on. The issue is your selector. It should be:

```js
const button = browser.react$("WithStyles(ForwardRef(Button))");
```

Why? Because MaterialUI (as well as Styled components) wrap their components in a bunch of HoC which makes selecting very difficult. You can see these HoCs in the React Dev Tools (which we *strongly* recommend you use:

![Screenshot 2019-09-03 at 11 45 41](https://user-images.githubusercontent.com/14321495/64162880-73f25180-ce40-11e9-9310-7a836d9f0cc9.png)

You can also see the `displayName` inside the React FiberNode (at the very end of the image):

![Screenshot 2019-09-03 at 11 47 12](https://user-images.githubusercontent.com/14321495/64162959-9ab08800-ce40-11e9-8eef-b82b22b3cc03.png)


We are aware that this makes it very difficult to select components, but there is very little we can do about this. If you have any suggestions feel free to open a PR and we'll discuss it.

One last thing, using `waitForExists` method will use CSS selectors with the given selector (even if you use `react$`). This is an issue with WebdriverIO and I will open a ticket in their repository about it. I suggest you wait until a non React element is displayed.

This test passes:

```js
describe('material-ui component', () => {
  it('go to about page and back main page', () => {
    browser.url('/'); //baseURLで指定したのがここで活きる
    browser.$('=Go to the about page').click(); //リンク名Selector
    const h1 = browser.$('h1')
    h1.waitForExist(5000)
    browser.pause(3000)
    const button = browser.react$("WithStyles(ForwardRef(Button))"); //React Selector
    button.click();
    browser.$('=Go to the about page').waitForExist(5000);
  });
});
```

**Comment by moeyashi** [comment]
The test passed!
I test with great attention to HOC from now on.

thank for opening the issue in WebdriverIO.

**Comment by gabriel-kohen-by** [comment]
Hi @baruchvlz , I'm trying to mimic your recommendation to @moeyashi  with MaterialUI without success. 
I'm trying to use the HoC reference without luck. The element is not found.
I'm using WDIO 7 which seems to use resq 1.10.0 on MacOS Catalina(Chrome 89).
I can't also seem to find the displayName you had mentioned.
`browser.react$("WithStyles(ForwardRef(LuiDrawer))")`
![image](https://user-images.githubusercontent.com/57095228/112708581-22c60a80-8e89-11eb-89f4-51411d7b2536.png)
Any pointers to what to search for. My next step was to write custom commands to abstract some of the mechanics to make it easier for WDIO users to use MaterialUI. However I will need to get over this up first.
