### ISSUE TITLE
Possibility of updating props and states in runtime

### ISSUE THREAD

**Issue by abhinaba-ghosh** [baruchvlz/resq#59]
I know the library is built to provide the Node information to the end user by quering React properties. I was just thinking about any possibilities of updating props and states using some crazy commands - setProps or setState. With Enzyme, it can be possible by mounting/shallowing the target component.But currently there is no solution where somebody doesn't have the access to the source code, like in e2e testing or integration testing.

**Comment by baruchvlz** [comment]
I'm not entirely sure this would be possible in e2e or integration tests because you would have to update the component (wether force, rehydration, or remounting) and this functionality does not exist in the DOM or in the instance of React within the DOM elements. This possible to do in testing libraries like Enzyme and React testing library because these are used for testing components in isolation and you can mount/hydrate these components utilising the ReactDOM api.

**Comment by abhinaba-ghosh** [comment]
I was thinking about the same terms. Just wanted to check how much we can leverage and enhance current the RESQ API.
