### ISSUE TITLE
byProps/byState should match all keys

### ISSUE THREAD

**Issue by ooorayray** [baruchvlz/resq#61]
### Current behavior

When passing a matcher with multiple keys, `.byProps`/`.byState` returns nodes that match any one of the given keys.

Example:
```ts
const filtered = myComponent.byProps({ prop1: 123, prop2: 'abc' })
console.log(filtered)
/*
{
    name: 'MyComponent',
    props: {
        prop1: 123,
        prop2: 'def',
    },
    // ...
}
*/
```

### Expected behavior

`.byProps`/`.byState` returns nodes that match ALL of the given keys.

Example:
```ts
const filtered = myComponent.byProps({ prop1: 123, prop2: 'abc' })
console.log(filtered)
/*
{
    name: 'MyComponent',
    props: {
        prop1: 123,
        prop2: 'abc',
    },
    // ...
}
*/
```

Failing test case: https://github.com/ooorayray/resq/commit/b502b830105736a80b2fccbd37d9b31ed9e55672

**Comment by baruchvlz** [comment]
Thanks for reporting and for the test case. I was able to pin point the error, I'm on my birthday holidays at the moment, but will fix this ASAP early next week along with #60 .

**Comment by baruchvlz** [comment]
Should be fixed in v1.9.0.

**Comment by rousku** [comment]
I still find current behavior unexpected. By writing `const filtered = myComponent.byProps({ prop1: 123, prop2: 'abc' })` I expect all `filtered` nodes have props `prop1: 123` AND `prop2: 'abc'`. I think [this](https://github.com/baruchvlz/resq/blob/a506daed2a5dcc7c9aac133a099bf28b2acbb119/tests/utils.test.js#L581) test case should fail because `b` doesn't have prop `foo`.

**Comment by baruchvlz** [comment]
@rousku The current match returns true if at least one of the properties match. There could be an optional flag to make it a strict match.

If you like you could open a PR and I would gladly review it :)
