### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by danieltroger** [baruchvlz/resq#75]
Hi guys, this utility is the most awesome thing I've tried out this week.

Since you seem to be knowledgable of react stuff I just wanted to ask if you know some generaliseable way to trigger a rerender? Because if I find a component with this and change its props the real DOM doesn't get updated and it would be nice to be able to do that. Are there any methods I could call?

**Comment by baruchvlz** [comment]
Hey @danieltroger , happy to hear you like the library. As for your question, it is not possible to trigger re-renders in React since the library is not really a React library rather it uses the browser DOM to traverse the elements with node attributes, for this reason, the library does not have access to the ReactDOM api (which is what libraries like Enzyme and React testing-library use internally to re-render during tests) thereby not being able to update the props.

_duplicate_: #59

**Comment by danieltroger** [comment]
Hey, it is actually possible to trigger a rerender!

Basically you do `resq$("component").node.__reactInternalInstance$XXXXX.return.stateNode.forceUpdate()`

Kudos to @deepsweet for discovering it.

**Comment by abhinaba-ghosh** [comment]
Hi @danieltroger @deepsweet do you have a code sample/repository for this. This is an awesome find. It can add tremendous value here https://github.com/abhinaba-ghosh/cypress-react-selector/issues/23

**Comment by danieltroger** [comment]
Hi @abhinaba-ghosh, I tried to make a video demo for you but I didn't succeed. It seems like it only works on certain react configurations. The react installation on facebook.com is especially interesting, it doesn't have __reactInternalInstance but rather __rreactInterrrnalFiber (sorry my keyboard is broken)

On this site it works: https://www.paulbrunngard.com I will make a demo and post it to your issue

**Comment by danieltroger** [comment]
@abhinaba-ghosh Sorry man, it seems like that it works is rarer than finding gold at the end of the rainbow. Getting a reliably method to rerender definitely needs more work.


https://user-images.githubusercontent.com/4047180/102997754-1945a300-4526-11eb-8a27-b95d75840d9c.mp4
